
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: v406E49rwwPSJZ3gScoaN7wkNW7yhjjz1eXvhS/qJ1E=
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
version: build{build}
image: Visual Studio 2017
clone_folder: C:\CKli-World\Kuinox-Projects\ChartsNite
branches:
  only:
    - master
    - develop
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
