
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: sQREuld5pncttq91qUMGmZs/7x0UFMQob6hcgbC+qqg=
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\Kuinox-Projects\ChartsNite
branches:
  only:
    - master
    - develop
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
